version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/ci"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
